### ISSUE TITLE
Unexpected error: <class 'AttributeError'>

### ISSUE THREAD

**Issue by MattGFFI** [TillMacher/TaxonTableTools#7]
Issue: Attempting to work through the tutorial using the tutorial files. However, whenever I reach try to merge replicates using the 'replicate consistency' function or use table filtering to extract Arthropods. I am met with the following message: "Unexpected error: <class 'AttributeError'>. 
![Screenshot 2023-08-03 085351](https://github.com/TillMacher/TaxonTableTools/assets/141228509/ea99731f-c02f-4cd6-ac5a-d7fd2ca750dc)

**Comment by onurdogan** [comment]
Hi @MattGFFI and @TillMacher, 

I also encountered the same error [1, 2] while running both "apscale_gui" and "TTT". However, [my colleague](https://github.com/MerjanK) recommended [using](https://stackoverflow.com/questions/76090979/xlsxwriter-object-has-no-attribute-save-did-you-mean-save/76119258#76119258) `writer.close()` instead of `writer.save()` in the following files which resolved the issue:

- `/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscale_gui/settings_file.py`
- `/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/taxontabletools/taxon_table_filtering.py`

Btw, downgrading the latest version of pandas might be an another [solution](https://github.com/TillMacher/apscale_gui/issues/7#issuecomment-1741742499).

best, Onur.

[1]: 
```Traceback (most recent call last):
  File "/usr/local/bin/apscale_gui", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscale_gui/__main__.py", line 534, in main
    apply_settings(settings_file, settings)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/apscale_gui/settings_file.py", line 77, in apply_settings
    writer.save()

AttributeError: 'XlsxWriter' object has no attribute 'save'
```

[2]: 
```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/taxontabletools", line 33, in <module>
    sys.exit(load_entry_point('taxontabletools==1.4.8', 'console_scripts', 'taxontabletools')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/taxontabletools/__main__.py", line 1460, in main
    taxon_filter(taxon_table_2_path, check_list, filter_taxonomic_level, appendix_name, threshold, path_to_outdirs, taxon_filter_method)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/taxontabletools/taxon_table_filtering.py", line 119, in taxon_filter
    writer.save()

AttributeError: 'XlsxWriter' object has no attribute 'save'
```

![image](https://github.com/TillMacher/TaxonTableTools/assets/11692156/ce7e0774-9ad8-40e7-a4c1-7eddc3cd9557)
![image](https://github.com/TillMacher/TaxonTableTools/assets/11692156/14031772-678a-45d2-a625-1245e568fd91)
