### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'append'

### ISSUE THREAD

**Issue by onurdogan** [TillMacher/TaxonTableTools#8]
Hi Till,

I am honoured to inform you that I have earned gold medal in the program crashing category again. I was competing in the 'Read Proportions > Calculate bar chart' section and encountered an [x_x] unexpected error [x_x], despite the accurate plotting of the heatmap and pie chart. This was a first-time occurrence, and the function had previously been functioning properly.

best, Onur.

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/taxontabletools", line 33, in <module>
    sys.exit(load_entry_point('taxontabletools==1.4.8', 'console_scripts', 'taxontabletools')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/taxontabletools/__main__.py", line 1696, in main
    read_proportions_bar(taxon_table_7_path, read_proportions_bar_taxonomic_level, path_to_outdirs, width_read_props_bar, heigth_read_props_bar, template, font_size, color_discrete_sequence)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/taxontabletools/read_proportions.py", line 292, in read_proportions_bar
    plot_df = plot_df.append(df)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'`

![Screenshot by Dropbox Capture](https://github.com/TillMacher/TaxonTableTools/assets/11692156/be0d5964-d530-4423-a182-a70a69e16aac)

**Comment by TillMacher** [comment]
This should be a quick fix. Maybe I'll manage over the weekend. Time is very limited this October :D

**Comment by onurdogan** [comment]
Hi again, 
Take your time. I also downgraded my pandas' latest version to 1.5.3 with `pip install pandas==1.5.3`  and turned back from`writer.close()` to `writer.save()`again, it is working properly right now. 
enjoy, Onur

**Comment by lmoliner** [comment]
> Hi again, Take your time. I also downgraded my pandas' latest version to 1.5.3 with `pip install pandas==1.5.3` and turned back from`writer.close()` to `writer.save()`again, it is working properly right now. enjoy, Onur

This also worked for me to solve an error during replicate merging.
